// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo0pvdZI-GNBgM79g9bORfrv1jI9o3hYo',
    appId: '1:125700177133:web:da3f255bdf8cd34fcb20e4',
    messagingSenderId: '125700177133',
    projectId: 'firestore-demo-a7da1',
    authDomain: 'firestore-demo-a7da1.firebaseapp.com',
    storageBucket: 'firestore-demo-a7da1.appspot.com',
    measurementId: 'G-GB71JZ7Y20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb6ofh31XhZ3Rn0ggBs89G5MKjKxVZwWk',
    appId: '1:125700177133:android:a2fdcc2cf97b2ae4cb20e4',
    messagingSenderId: '125700177133',
    projectId: 'firestore-demo-a7da1',
    storageBucket: 'firestore-demo-a7da1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx-8KQRy-dJ3X78aklzJ73f8UnhinYHyE',
    appId: '1:125700177133:ios:572c8eae46d94e79cb20e4',
    messagingSenderId: '125700177133',
    projectId: 'firestore-demo-a7da1',
    storageBucket: 'firestore-demo-a7da1.appspot.com',
    iosClientId: '125700177133-v87tpkk2l46trsk68rhooojm6u553sgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx-8KQRy-dJ3X78aklzJ73f8UnhinYHyE',
    appId: '1:125700177133:ios:572c8eae46d94e79cb20e4',
    messagingSenderId: '125700177133',
    projectId: 'firestore-demo-a7da1',
    storageBucket: 'firestore-demo-a7da1.appspot.com',
    iosClientId: '125700177133-v87tpkk2l46trsk68rhooojm6u553sgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreDemo',
  );
}
